### ISSUE TITLE
no-subdomain option doesn't allow to install from YunoHost

### ISSUE THREAD

**Issue by leonbur** [YunoHost-Apps/huginn_ynh#9]
While attempting to install from YunoHost's catalog I'm getting the error:

`Sorry, this app must be installed on a domain of its own, but other apps are already installed on the domain '***.com'. You could use a subdomain dedicated to this app instead.`

Usually there's a text field to enter the a URL path for the app but not in this form.

YunoHost 4.3.6.3

**Comment by yalh76** [comment]
Huginn can't be installed in a subpath
